-- Explore Jordan Supabase schema plan
-- Current frontend data source remains the JSON files in /data.
-- These tables are prepared for a future Supabase PostgreSQL integration.

-- Categories define reusable labels for destinations, activities, and accommodations.
CREATE TABLE IF NOT EXISTS categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Destinations store Jordan places such as Petra, Wadi Rum, Amman, and Wadi Mujib.
CREATE TABLE IF NOT EXISTS destinations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  city text,
  category text,
  short_description text,
  long_description text,
  image text,
  map_link text,
  official_link text,
  tags text[],
  created_at timestamptz DEFAULT now()
);

-- Activities store travel experiences such as hiking, diving, tours, and Dead Sea floating.
CREATE TABLE IF NOT EXISTS activities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  location text,
  category text,
  short_description text,
  long_description text,
  image text,
  duration text,
  price_range text,
  map_link text,
  tags text[],
  created_at timestamptz DEFAULT now()
);

-- Accommodations store stay types such as resorts, eco lodges, desert camps, and boutique hotels.
CREATE TABLE IF NOT EXISTS accommodations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  city text,
  type text,
  price_range text,
  short_description text,
  long_description text,
  image text,
  booking_link text,
  tags text[],
  created_at timestamptz DEFAULT now()
);
